server:
  port: 8082
spring:
  application:
    name: alert-service
  datasource:
    url: jdbc:postgresql://localhost:5432/coin_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: checkAlerts
    stream:
      bindings:
        checkAlerts-in-0:
          destination: crypto-prices
          group: alert-service-group
      kafka:
        binder:
          brokers: localhost:9092
grpc:
  client:
    market-data-client:
      address: static://localhost:9090
      negotiation-type: plaintext
